// ── Default settings extracted from AppContext to keep file size manageable ──

// Safe defaults for Featherless AI — never allow live handoff by default
export const DEFAULT_FEATHERLESS_SETTINGS = {
  enabled: false,
  modelName: 'deepseek-ai/DeepSeek-V4-Pro',
  temperature: 0.1,
  maxTokens: 4000,
  timeoutSeconds: 120,
  minConfidence: 50,
  minEdge: 3,
  minExpectedROI: 1,
  paperTradeOnly: true,
  allowLiveHandoff: false,
  storeLogs: true,
  minOdds: 1.5,
  maxOdds: 50,
  minLiquidity: 20,
  timeWindowStart: 500,
  timeWindowEnd: 30,
  stakingMode: 'confidence_weighted_fractional_kelly',
  webResearchEnabled: false,
  aiDecisionMode: 'strict',
  requireExternalFormData: false,
  targetPaperBetsPerDay: 'low',
  maxSpread: 7,
  winMinOdds: 1.5, winMaxOdds: 50, winMinLiquidity: 20, winMaxSpreadTicks: 7, winMinEdge: 3, winMinROI: 1,
  placeMinOdds: 1.2, placeMaxOdds: 30, placeMinLiquidity: 10, placeMaxSpreadTicks: 7, placeMinEdge: 2, placeMinROI: 1,
  h2hMinOdds: 1.2, h2hMaxOdds: 15, h2hMinLiquidity: 10, h2hMaxSpreadTicks: 5, h2hMinEdge: 3, h2hMinROI: 1,
  allowHedging: false,
  debugScanMode: false,
  externalSearchEnabled: false,
  maxExternalProbabilityAdjustment: 0.05,
  minExternalSourceCount: 2,
  minExternalDataQuality: 50,
  requireExternalSearchForLiveBetting: false,
  externalSearchCacheTtlMinutes: 5,
  // ── Race Assessment Architecture ──
  featherlessAlwaysRequired: true,
  requireFullRacePack: true,
  maxRacesPerCycle: 1,
  maxRunnersPerRacePack: 30,
  maxMarketsPerRacePack: 10,
  includeOpenAIResearchInRacePack: true,
  includeRiskContextInRacePack: true,
  allowMarketOnlyFallbackInDebug: true,
  allowMarketOnlyFallbackInPaperProof: true,
  allowMarketOnlyFallbackInNormalMode: false,
  featherlessTimeoutMs: 120000,
  featherlessStrictJson: true,
  paperProofExternalSearchEnabled: false,
  // ── Favourite Value Context ──
  favouriteContextEnabled: true,
  favouriteContextMaxProbabilityAdjustment: 0.03,
  favouriteStrongConfidenceBoost: 5,
  favouriteWeakConfidencePenalty: 10,
  requireFavouriteContextForWinMarket: false,
  allowFavouriteLayOnlyWhenVulnerable: true,
  racePackCacheTtlMinutes: 30,
  aiResultCacheTtlSeconds: 90,
  rerunAiOnMajorPriceMove: true,
  majorPriceMoveTicks: 5,
  prewarmOpenAIWithinMinutes: 30,
  completedRaceRetentionHours: 6,
};

export const DEFAULT_BOT_SETTINGS = {
  botEnabled: false,
  botMode: 'demo',
  scanIntervalSeconds: 30,
  selectedStrategies: ['Featherless AI Value Decision Engine'],
  autoPaperTradingEnabled: true,
  liveTradingLocked: true,
  liveTradingEnabled: false,
  requireLiveConfirmationText: true,
  confirmationText: 'ENABLE LIVE TRADING',
  maxBotCyclesPerHour: 60,
  stopOnApiError: true,
  stopOnDailyLoss: true,
  stopOnMaxDrawdown: true,
  stopOnLosingStreak: true,
  stopOnEmergency: true,
};