import{describe,expect,it}from'vitest';
import{buildCalculationResult,buildPartialMatchCalculations,calcBackEV,calcLayEV,calcKellyStake,calcLayKellyStake}from'./exchangeMath';
import{calcProofStake,proofLiabilityLimit}from'./paperProofDefaults';
import{calculateScalpProfit,calculateScalpTargetPrice,calculateStopLossPrice}from'./tickLadder';
const optimum=(p,o,c,side)=>{let best=0,score=-Infinity;for(let i=0;i<=100000;i++){const x=i/100000/(o-1),a=side==='BACK'?Math.log(1+x*(o-1)*(1-c))*p+Math.log(1-x)*(1-p):Math.log(1+x*(1-c))*(1-p)+Math.log(1-x*(o-1))*p;if(a>score){score=a;best=x;}}return best;};
describe('golden exchange maths',()=>{
it('BACK EV ROI breakeven and commission edge',()=>{const r=buildCalculationResult({side:'BACK',probabilityDecimal:.7462958038610861,odds:1.4,commissionRateDecimal:.08,stake:100});expect(r.rawProbabilityEdge).toBeCloseTo(.03201009,7);expect(r.commissionAdjustedEdge).toBeCloseTo(.01530165,7);expect(r.breakevenProbability).toBeCloseTo(.73099415,7);expect(calcBackEV(.4,3,.05,100)).toMatchObject({ev:16,roi:.16,liability:100});});
it('LAY EV liability ROI and breakeven',()=>{const r=buildCalculationResult({side:'LAY',probabilityDecimal:.15,odds:5,commissionRateDecimal:.05,stake:100});expect(r).toMatchObject({ev:20.75,roi:.051875,liability:400});expect(r.breakevenProbability).toBeCloseTo(.95/4.95,12);expect(calcLayEV(.15,5,.05,100).liability).toBe(400);});
it('Kelly matches numerical log-growth optima',()=>{const back=calcKellyStake(.4,3,10000,1,1,.05);expect(back.kellyFraction).toBeCloseTo(optimum(.4,3,.05,'BACK'),4);const lay=calcLayKellyStake(.1,4,10000,1,1,.05);expect(lay.kellyFraction).toBeCloseTo(optimum(.1,4,.05,'LAY'),4);expect(calcKellyStake(.2,3,10000,1,1,.05).stake).toBe(0);expect(calcLayKellyStake(.4,3,10000,1,1,.05).stake).toBe(0);});
it('recomputes partial BACK and LAY maths',()=>{const back=buildPartialMatchCalculations({side:'BACK',probabilityDecimal:.5,odds:3,commissionRateDecimal:.05,requestedStake:2,matchedStake:1,remainingStake:1});expect(back.matchedCalculation.liability).toBe(1);const lay=buildPartialMatchCalculations({side:'LAY',probabilityDecimal:.05,odds:10,commissionRateDecimal:.05,requestedStake:2,matchedStake:1,remainingStake:1});expect(lay.requestedCalculation.liability).toBe(18);expect(lay.matchedCalculation.liability).toBe(9);expect(lay.remainingUnmatchedCalculation.liability).toBe(9);});
it('hard caps proof liability at long odds',()=>{expect(proofLiabilityLimit({maxLayLiability:1500})).toBe(25);expect(calcProofStake('LAY',1000,{maxStake:5,maxLayLiability:1500})).toBe(0);});
it('uses correct scalp directions and net commission',()=>{expect(calculateScalpTargetPrice(3,1,'BACK')).toBeLessThan(3);expect(calculateStopLossPrice(3,1,'BACK')).toBeGreaterThan(3);expect(calculateScalpTargetPrice(3,1,'LAY')).toBeGreaterThan(3);expect(calculateStopLossPrice(3,1,'LAY')).toBeLessThan(3);expect(calculateScalpProfit(3,2.9,10,'BACK',.05)).toBeGreaterThan(0);expect(calculateScalpProfit(3,3.1,10,'BACK',.05)).toBeLessThan(0);expect(calculateScalpProfit(3,3.1,10,'LAY',.05)).toBeGreaterThan(0);expect(calculateScalpProfit(3,2.9,10,'LAY',.05)).toBeLessThan(0);});
it('proves invariant properties over randomized inputs',()=>{for(let i=0;i<250;i++){const p=Math.random(),odds=1.01+Math.random()*998.99,stake=Math.random()*100,c=Math.random()*.2;for(const side of['BACK','LAY']){const r=buildCalculationResult({side,probabilityDecimal:p,odds,commissionRateDecimal:c,stake});expect(r.mathematicalInvariantsPassed).toBe(true);if(side==='BACK'){expect(r.ev).toBeGreaterThanOrEqual(-stake-1e-8);expect(r.roi).toBeGreaterThanOrEqual(-1-1e-8);expect(r.liability).toBe(stake);}else{expect(r.ev).toBeGreaterThanOrEqual(-r.liability-1e-8);expect(r.liability).toBeCloseTo(stake*(odds-1),8);}}}});
});