import { describe, expect, it } from 'vitest';
import { createDebugPackageFiles } from './debugPackageFiles';
import { parseRaceNumber, resolveNumberOfWinners } from './marketClusterer';

const runners=Array.from({length:12},(_,index)=>({marketId:'1.1',selectionId:String(index+1),runnerName:`Runner ${index+1}`,status:'ACTIVE',bestBackPrice:2+index*.1,bestBackSize:20,bestLayPrice:2.02+index*.1,bestLaySize:20,lastPriceTraded:2.01,totalMatched:100}));
const opportunities=Array.from({length:19},(_,index)=>({opportunityId:`opp-${index+1}`,marketId:'1.1',marketName:'R1 1400m Mdn',marketType:'WIN',runnerName:`Runner ${(index%12)+1}`,selectionId:String((index%12)+1),side:index%2?'LAY':'BACK',odds:2,modelProbability:.4,impliedProbability:.5,finalProbabilityUsedInEV:.4,stake:10,liability:10,commissionRate:.05,ev:index===0?-.5:.1,roi:index===0?-.05:.01,edge:index===0?-.1:.01,breakevenProbability:.5,mathematicalInvariantsPassed:true,decision:index===0?'BET':'NO_BET',gatesPassed:index===0,failedGate:index===0?null:'EDGE_BELOW_MINIMUM',blockers:index===0?[]:['EDGE_BELOW_MINIMUM']}));
const summary={allOpportunitiesSnapshot:opportunities,opportunityLogCompleteness:'complete_cycle_snapshot',totalOpportunities:19,selectedRaceKey:'race-1',selectedRaceName:'R1 1400m Mdn',selectedRaceStartTime:'2026-07-12T01:55:00Z',selectedRaceMarketDetails:[{marketId:'1.1',marketName:'R1 1400m Mdn',marketType:'WIN',marketTypeCode:'WIN',accepted:true,activeRunnerCount:12}],selectedRaceRunnerSnapshot:runners,connectionDiagnostics:{priceFeedStatus:'LIVE'}};
const cycle={cycleId:'cycle-1',cycleNumber:10,finishedAt:'2026-07-11T01:00:00Z',ordersCreated:0,scanSummary:summary};
const state={settings:{defaultCommissionRate:.05,defaultTimeWindowStartSeconds:86400,defaultTimeWindowEndSeconds:1},featherlessSettings:{timeWindowStart:86400,timeWindowEnd:1},botSettings:{},markets:[],runners:[],paperOrders:[],botCycles:[cycle],exchangeOpportunities:[],auditLogs:[]};
const build=()=>createDebugPackageFiles(state);

function csvRows(csv){const lines=csv.trim().split('\n');const parse=line=>{const values=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'){value+='"';i++;}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){values.push(value);value='';}else value+=char;}values.push(value);return values;};const headers=parse(lines[0]);return lines.slice(1).map(line=>Object.fromEntries(headers.map((header,index)=>[header,parse(line)[index]])));}

describe('debug package canonical consistency',()=>{
  it('uses the same post-gate decision in top opportunities and opportunity log',()=>{const result=build();const top=JSON.parse(result.files['opportunities/top-opportunities.json'])[0];const log=csvRows(result.files['opportunities/opportunity-log.csv'])[0];expect(top).toMatchObject({decision:'NO_BET',gatesPassed:false,failedGate:'NON_POSITIVE_EV'});expect(log).toMatchObject({Decision:'NO_BET',FailedGate:'NON_POSITIVE_EV'});expect(top.blockers).toContain('NON_POSITIVE_EV');});
  it('never exports negative EV as BET in any opportunity JSON',()=>{const result=build();for(const path of ['opportunities/opportunities-current.json','opportunities/top-opportunities.json','opportunities/top-rejected.json']){const rows=JSON.parse(result.files[path]);expect(rows.filter(row=>Number(row.ev)<=0).every(row=>row.decision==='NO_BET'&&row.failedGate==='NON_POSITIVE_EV')).toBe(true);}});
  it('exports only runner-shaped records',()=>{const rows=JSON.parse(build().files['markets/runners-current.json']);expect(rows).toHaveLength(12);expect(Object.keys(rows[0]).sort()).toEqual(['bestBackPrice','bestBackSize','bestLayPrice','bestLaySize','lastPriceTraded','marketId','runnerName','runnerNameHydrated','runnerNameHydrationSource','selectionId','status','totalMatched'].sort());expect(rows[0]).not.toHaveProperty('opportunityId');expect(rows[0]).not.toHaveProperty('ev');});
  it('validates twelve actual runners rather than nineteen opportunity rows',()=>{const validation=JSON.parse(build().files['calculations/market-book-validation.json']);expect(validation[0].activeRunnerCount).toBe(12);expect(validation[0].runners).toHaveLength(12);expect(validation[0].errors).not.toContain('DUPLICATE_SELECTION_ID');});
  it('includes invariant and authority status for every calculation',()=>{const rows=JSON.parse(build().files['calculations/calculation-snapshots.json']);expect(rows).toHaveLength(19);for(const row of rows){expect(typeof row.mathematicalInvariantsPassed).toBe('boolean');expect(Object.keys(row.rankedCalculation).length).toBeGreaterThan(0);expect(typeof row.valuesMatched).toBe('boolean');expect(row).toHaveProperty('mismatchReason');}expect(rows[0]).toMatchObject({finalAuthorityRecalculation:'not_reached',finalAuthorityNotReachedReason:'NON_POSITIVE_EV'});});
  it('populates active window timestamps',()=>{const report=JSON.parse(build().files['race-day/race-monitoring-diagnostics.json']);expect(report).toMatchObject({windowStartSeconds:86400,windowEndSeconds:1,selectedRaceWindowOpensAt:'2026-07-11T01:55:00.000Z',selectedRaceWindowClosesAt:'2026-07-12T01:54:59.000Z'});});
  it('parses race one and infers one WIN winner',()=>{expect(parseRaceNumber('R1 1400m Mdn')).toBe(1);expect(resolveNumberOfWinners({marketName:'R1 1400m Mdn',marketTypeCode:'WIN'})).toEqual({numberOfWinners:1,numberOfWinnersSource:'INFERRED'});const csv=build().files['cycles/decision-log.csv'];expect(csv).toContain('SelectedRaceNumber');expect(csvRows(csv)[0].SelectedRaceNumber).toBe('1');});
  it('marks legacy cycles with missing candidate snapshots',()=>{const legacy={cycleId:'old',cycleNumber:9,ordersCreated:0,scanSummary:{totalOpportunities:4,topOpportunities:[opportunities[1]]}};const result=createDebugPackageFiles({...state,botCycles:[cycle,legacy]});const rows=csvRows(result.files['cycles/decision-log.csv']);expect(rows[0]).toMatchObject({LegacyIncomplete:'false',MissingCandidateSnapshot:'false'});expect(rows[1]).toMatchObject({LegacyIncomplete:'true',MissingCandidateSnapshot:'true'});});
});