import { CYCLE_EXPORT_COLUMNS, OPPORTUNITY_EXPORT_COLUMNS, cycleToRow, opportunitiesToRows } from '@/lib/decisionLogExport';
import { rowsToCSV } from '@/lib/csvExport';
import { deepRedact } from '@/lib/debugRedaction';
import { buildCalculationSnapshots, buildCommissionSnapshots, buildMarketBookValidation } from '@/lib/debugCalculations';
import { enrichLatestCycleForExport, resolveLatestOpportunitySnapshot, resolveMarketAndRunnerSnapshots } from '@/lib/debugPackageSources';
import { parseRaceNumber, resolveNumberOfWinners } from '@/lib/marketClusterer';
import { reconcileRiskExposure } from '@/lib/riskExposure';
import { canonicalRaceIdentity } from '@/lib/raceIdentity';

export const FULL_DEBUG_PATHS = ['README-debug-package.txt','debug-summary.json','app-version.json','settings/app-settings.json','settings/bot-settings.json','settings/featherless-settings.json','settings/risk-settings.json','connection/betfair-connection-status.json','connection/price-feed-diagnostics.json','race-day/race-day-cache-summary.json','race-day/selected-race.json','race-day/selected-race-market-details.json','race-day/race-monitoring-diagnostics.json','markets/markets-current.json','markets/runners-current.json','markets/loaded-markets-table.json','opportunities/opportunities-current.json','opportunities/top-opportunities.json','opportunities/top-rejected.json','opportunities/opportunity-log.csv','cycles/decision-log.csv','cycles/bot-cycles.json','orders/paper-orders.csv','orders/paper-orders.json','orders/open-risk-exposure.json','settlement/settlement-status.json','settlement/settlement-worker-runs.json','ai/ai-observability.json','ai/featherless-last-response.json','ai/openai-web-search-diagnostics.json','calculations/calculation-snapshots.json','calculations/commission-snapshots.json','calculations/market-book-validation.json','errors/audit-logs.json','errors/recent-errors.json','system/schema-contract-check.json','system/local-storage-snapshot.json','system/bot-scheduler-diagnostics.json','system/race-identity-consistency.json','settlement/settlement-frequency-diagnostics.json','orders/risk-exposure-reconciliation.json'];
export const MINIMAL_DEBUG_PATHS = ['README-debug-package.txt','debug-summary.json','cycles/decision-log.csv','opportunities/opportunity-log.csv','orders/paper-orders.csv','race-day/race-monitoring-diagnostics.json','race-day/selected-race-market-details.json','ai/ai-observability.json','calculations/calculation-snapshots.json','errors/recent-errors.json'];

const json = value => JSON.stringify(deepRedact(value), null, 2);
const idOf = item => String(item?.betfairMarketId || item?.marketId || item?.id || '');
const openStatuses = new Set(['pending','executable','matched','unmatched','partially_matched']);

export function createDebugPackageFiles(state, { minimal = false, timestamp = new Date().toISOString(), exportErrors = [] } = {}) {
  const errors = [...exportErrors];
  const cycles = state.botCycles || [];
  const originalLatest = cycles[0] || {};
  const originalSummary = originalLatest.scanSummary || state.lastExchangeDiagnostics || {};
  const snapshot = resolveLatestOpportunitySnapshot(state, originalLatest, originalSummary);
  const exportCycles = enrichLatestCycleForExport(cycles, snapshot);
  const latest = exportCycles[0] || originalLatest;
  const summary = latest.scanSummary || originalSummary;
  const opportunities = Array.isArray(summary.opportunityLog) ? summary.opportunityLog : snapshot.opportunities;
  const opportunityRows = opportunitiesToRows(exportCycles);
  let cycleRows = [];
  const {markets,runners,loadedMarkets,selectedDetails} = resolveMarketAndRunnerSnapshots(state, latest, summary);
  const orders = state.paperOrders || [];
  const riskExposure=reconcileRiskExposure(orders);
  const activeOrders=riskExposure.orders;
  const unresolved=activeOrders;
  const raceMonitoring = reconcileRaceRunnerCounts(populateRaceMonitoring(pickRaceMonitoring(summary), state), runners);
  const finalizedExportCycles=exportCycles.map((cycle,index) => index === 0 ? {...cycle,scanSummary:{...(cycle.scanSummary || {}),...raceMonitoring}} : cycle);
  cycleRows = finalizedExportCycles.map(cycleToRow);
  const ai = buildAiDiagnostics(summary, opportunities);
  const recentErrors = [...(state.auditLogs || []).filter(log => ['error','critical'].includes(log.severity)), ...(state.lastDebugScanError ? [{source:'debug_scan',error:state.lastDebugScanError}] : []), ...(state.betfairConnection?.lastConnectionError ? [{source:'betfair_connection',error:state.betfairConnection.lastConnectionError}] : [])].slice(0, 100);
  const calculations = safeSection('calculation-snapshots', () => buildCalculationSnapshots(opportunities, latest.finishedAt || timestamp), [], errors);
  const acceptedMarketIds = selectedDetails.filter(item => item.accepted).map(item => item.normalizedMarketId || item.marketId).filter(Boolean);
  const sentMarketIds = acceptedMarketIds.length ? acceptedMarketIds : [...new Set(opportunities.map(idOf).filter(Boolean))];
  const marketBookValidation = safeSection('market-book-validation', () => buildMarketBookValidation(markets, runners, sentMarketIds), [], errors);
  const selectedRace = { raceKey:raceMonitoring.selectedRaceKey, eventId:raceMonitoring.selectedRaceEventId, venue:raceMonitoring.selectedRaceVenue, raceNumber:raceMonitoring.selectedRaceNumber, name:raceMonitoring.selectedRaceName, startTime:raceMonitoring.selectedRaceStartTime };
  const connection = summary.connectionDiagnostics || {};
  const apiConnected = connection.betfairApiConnected ?? connection.apiConnected ?? state.apiConnected ?? false;
  const streamConnected = connection.streamConnected ?? ['connected','polling'].includes(state.betfairConnection?.streamConnectionStatus);
  const timeWindowStartSeconds = Number(summary.windowStartSeconds ?? summary.opportunityFunnel?.windowStartSeconds ?? state.featherlessSettings?.timeWindowStart ?? state.settings?.defaultTimeWindowStartSeconds ?? 500);
  const timeWindowEndSeconds = Number(summary.windowEndSeconds ?? summary.opportunityFunnel?.windowEndSeconds ?? state.featherlessSettings?.timeWindowEnd ?? state.settings?.defaultTimeWindowEndSeconds ?? 30);
  const windowMode = timeWindowStartSeconds >= 86400 || latest.paperProofMode || summary.paperProofMode ? 'PROOF_WIDE_WINDOW' : 'NORMAL_WINDOW';
  const debugSummary = { appName:'Betfair Edge Lab', exportTimestamp:timestamp, currentPage:state.currentPage || '/debug', mode:state.appMode || latest.botMode, paperMode:true, proofMode:windowMode === 'PROOF_WIDE_WINDOW', botStatus:state.botState?.running ? (state.botState?.paused ? 'paused' : 'running') : 'stopped', apiConnected:!!apiConnected, streamConnected:!!streamConnected, priceFeedStatus:connection.priceFeedStatus || 'UNAVAILABLE', selectedRace, markets:connection.marketFeedDiagnostics?.marketsInMemory ?? summary.marketFeedDiagnostics?.marketsInMemory ?? summary.totalMarketsLoaded ?? markets.length, runners:summary.marketFeedDiagnostics?.runnersInMemory ?? summary.totalRunnerCount ?? runners.length, opportunities:Number(summary.totalOpportunities ?? opportunities.length), opportunityLogCompleteness:snapshot.opportunityLogCompleteness, paperOrders:orders.length, unresolvedSettlements:unresolved.length, latestCycleDecision:latest.cycleOutcome || (latest.ordersCreated ? 'BET' : 'NO_BET'), latestFailedGate:summary.bestRejectedCandidate?.failedGate || summary.failedGate || null, latestNoBetReason:latest.noBetReason || summary.noBetReason || null, windowMode, timeWindowStartSeconds, timeWindowEndSeconds, windowWarning:windowMode === 'PROOF_WIDE_WINDOW' ? 'Normal 30–300 second window is not active.' : null };
  const files = {
    'README-debug-package.txt':buildReadme(debugSummary), 'debug-summary.json':json(debugSummary), 'app-version.json':json({ appName:'Betfair Edge Lab', exportSchemaVersion:'1.0.0', generatedAt:timestamp }),
    'settings/app-settings.json':json(state.settings || {}), 'settings/bot-settings.json':json(state.botSettings || {}), 'settings/featherless-settings.json':json(state.featherlessSettings || {}), 'settings/risk-settings.json':json(buildRiskSettings(state.settings || {}, state.riskStatus)),
    'connection/betfair-connection-status.json':json({ ...state.betfairConnection, apiConnected, streamConnected }), 'connection/price-feed-diagnostics.json':json(connection),
    'race-day/race-day-cache-summary.json':json({ raceDayLoaded:summary.raceDayLoaded, raceDayLoadedAt:summary.raceDayLoadedAt, totalDayRaces:summary.totalDayRaces, totalDayMarkets:summary.totalDayMarkets, cachedRacePacks:summary.cachedRacePacks }),
    'race-day/selected-race.json':json(selectedRace), 'race-day/selected-race-market-details.json':json(raceMonitoring.selectedRaceMarketDetails || []), 'race-day/race-monitoring-diagnostics.json':json(raceMonitoring),
    'markets/markets-current.json':json(markets), 'markets/runners-current.json':json(runners), 'markets/loaded-markets-table.json':json(loadedMarkets),
    'opportunities/opportunities-current.json':json(opportunities), 'opportunities/top-opportunities.json':json(opportunities.slice(0, 20)), 'opportunities/top-rejected.json':json(opportunities.filter(item => item.gatesPassed !== true).slice(0, 10)), 'opportunities/opportunity-log.csv':rowsToCSV(deepRedact(opportunityRows), OPPORTUNITY_EXPORT_COLUMNS),
    'cycles/decision-log.csv':rowsToCSV(deepRedact(cycleRows), CYCLE_EXPORT_COLUMNS), 'cycles/bot-cycles.json':json(finalizedExportCycles),
    'orders/paper-orders.csv':rowsToCSV(deepRedact(orders), inferColumns(orders)), 'orders/paper-orders.json':json(orders), 'orders/open-risk-exposure.json':json(riskExposure), 'orders/risk-exposure-reconciliation.json':json(riskExposure),
    'settlement/settlement-status.json':json({ report:state.settlementReport, unresolvedCount:unresolved.length, unresolvedOrders:unresolved }), 'settlement/settlement-worker-runs.json':json(state.settlementWorkerRuns || []), 'settlement/settlement-frequency-diagnostics.json':json(buildSettlementFrequency(state.settlementWorkerRuns || [])),
    'ai/ai-observability.json':json(ai), 'ai/featherless-last-response.json':json((state.aiDecisions || [])[0] || summary.aiDecisions?.[0] || null), 'ai/openai-web-search-diagnostics.json':json({...(summary.externalSearchDiagnostics || {}),openAIWebSearchStatus:ai.openAIWebSearchStatus,nextRetryAt:ai.nextRetryAt,backoffSeconds:ai.backoffSeconds,openAIWebSearchErrorType:ai.openAIWebSearchErrorType}),
    'calculations/calculation-snapshots.json':json(calculations), 'calculations/commission-snapshots.json':json(safeSection('commission-snapshots', () => buildCommissionSnapshots(markets, opportunities, state.settings || {}), {markets:[],opportunities:[],selectedOpportunities:[]}, errors)), 'calculations/market-book-validation.json':json(marketBookValidation),
    'errors/audit-logs.json':json(state.auditLogs || []), 'errors/recent-errors.json':json(recentErrors), 'system/schema-contract-check.json':json(buildSchemaCheck(state, cycleRows, opportunityRows, raceMonitoring, riskExposure)), 'system/local-storage-snapshot.json':json(state.localStorageSnapshot || {}), 'system/bot-scheduler-diagnostics.json':json(state.schedulerDiagnostics || {}), 'system/race-identity-consistency.json':json(buildRaceIdentityConsistency(markets,opportunities,orders,raceMonitoring)),
  };
  const wanted = minimal ? MINIMAL_DEBUG_PATHS : FULL_DEBUG_PATHS;
  const selected = Object.fromEntries(wanted.map(path => [path, files[path]]));
  if (errors.length) selected['errors/export-errors.json'] = json(errors);
  return { files:selected, summary:debugSummary, counts:{ decisionLogRows:cycleRows.length, opportunityLogRows:opportunityRows.length, paperOrderRows:orders.length }, exportErrors:errors };
}

function safeSection(section, build, fallback, errors) { try { return build(); } catch (error) { errors.push({section,error:error.message}); return fallback; } }
function inferColumns(rows) { return (rows[0] ? Object.keys(rows[0]).filter(key => !key.startsWith('_')) : ['id']).map(key => ({key,label:key})); }
function buildRiskSettings(settings, riskStatus) { const keys=['bankroll','paperBankroll','baseStake','maxStake','maxStakePercent','maxLayLiability','dailyLossLimit','weeklyLossLimit','maxMarketExposure','maxOpenOrders','maxUnmatchedOrders','maxTradesPerMarket','maxTradesPerRunner','maxTradesPerDay','riskLimitsDisabled']; return { ...Object.fromEntries(keys.map(key => [key, settings[key]])), currentStatus:riskStatus }; }
function reconcileRaceRunnerCounts(report, runners) { const selectedRaceMarketDetails=(report.selectedRaceMarketDetails || []).map(market => { const id=String(market.normalizedMarketId || market.marketId || market.betfairMarketId || ''); const matching=runners.filter(runner => String(runner.normalizedMarketId || runner.marketId || runner.betfairMarketId || '')===id); const active=matching.filter(runner => runner.status==='ACTIVE'); return {...market,runnerCount:matching.length,activeRunnerCount:active.length,pricedRunnerCount:active.filter(runner => Number(runner.bestBackPrice)>0 || Number(runner.bestLayPrice)>0).length}; }); return {...report,selectedRaceMarketDetails}; }
function populateRaceMonitoring(report, state) { const start=report.selectedRaceStartTime ? new Date(report.selectedRaceStartTime).getTime() : NaN; const windowStartSeconds=Number(report.windowStartSeconds ?? state.featherlessSettings?.timeWindowStart ?? state.settings?.defaultTimeWindowStartSeconds ?? 500); const windowEndSeconds=Number(report.windowEndSeconds ?? state.featherlessSettings?.timeWindowEnd ?? state.settings?.defaultTimeWindowEndSeconds ?? 30); const selectedRaceMarketDetails=(report.selectedRaceMarketDetails || []).map(market => ({...market,...resolveNumberOfWinners(market)})); const selectedRaceNumber=report.selectedRaceNumber || parseRaceNumber(report.selectedRaceName,selectedRaceMarketDetails[0]?.marketName,selectedRaceMarketDetails[0]?.raceName) || 0; const selectedRaceKey=selectedRaceNumber>0&&/^race:.*:0:\d+$/.test(report.selectedRaceKey || '') ? String(report.selectedRaceKey).replace(/:0:(\d+)$/,`:${selectedRaceNumber}:$1`) : report.selectedRaceKey; return {...report,selectedRaceKey,selectedRaceNumber,selectedRaceMarketDetails,windowStartSeconds,windowEndSeconds,selectedRaceWindowOpensAt:report.selectedRaceWindowOpensAt || (Number.isFinite(start) ? new Date(start-windowStartSeconds*1000).toISOString() : null),selectedRaceWindowClosesAt:report.selectedRaceWindowClosesAt || (Number.isFinite(start) ? new Date(start-windowEndSeconds*1000).toISOString() : null)}; }
function pickRaceMonitoring(summary) { const keys=['selectedRaceKey','selectedRaceEventId','selectedRaceVenue','selectedRaceNumber','selectedRaceName','selectedRaceStartTime','secondsToStart','raceMonitoringStatus','cyclesScannedOnThisRace','firstCycleSeenForRace','latestCycleSeenForRace','raceLocked','raceLockReason','activeOrderExistsForRace','activeOrderIdsForRace','reasonStillScanningRace','selectedRaceUniqueMarketCount','selectedRaceWinMarketCount','selectedRacePlaceMarketCount','selectedRaceH2HMarketCount','selectedRaceDuplicateMarketCount','duplicateMarketRecordDetected','diagnosticError','primaryWinMarketId','secondaryWinMarketIds','primaryMarketSelectionReason','selectedRaceMarketDetails','windowStartSeconds','windowEndSeconds','selectedRaceWindowOpensAt','selectedRaceWindowClosesAt']; return Object.fromEntries(keys.map(key => [key, summary[key] ?? summary.raceMonitoring?.[key] ?? null])); }
function buildAiDiagnostics(summary, opportunities) { const trace=summary.aiObservability?.at?.(-1) || {}; const source=opportunities.find(item => item.selectedAsFinalCandidate) || opportunities[0] || {}; const web=summary.externalSearchDiagnostics || {}; return { featherlessStatus:summary.featherlessStatus || trace.aiCallStatus || 'not_requested', featherlessCalled:(summary.aiCallsMade || 0)>0, featherlessCacheHit:(summary.aiCacheHits || 0)>0, featherlessRunnerCountReturned:summary.aiRunnerCountReturned || trace.aiRunnerCountReturned || trace.aiResponseRunnerCount || 0, featherlessH2HCountReturned:summary.raceAssessmentDiagnostics?.totalH2HProbabilitiesReturned || 0, featherlessLatencyMs:trace.aiLatencyMs || summary.raceAssessmentDiagnostics?.featherlessAvgLatencyMs || 0, featherlessError:summary.featherlessError || trace.aiErrorMessage || null, openAIWebSearchStatus:summary.openAIWebSearchStatus || web.latestSearchStatus || 'not_requested', openAIWebSearchError:summary.openAIWebSearchError || web.perEventResults?.find(item=>item.errorMessage)?.errorMessage || null, nextRetryAt:summary.openAIWebSearchNextRetryAt || web.nextRetryAt || null, openAIWebSearchErrorType:summary.openAIWebSearchErrorType || web.openAIWebSearchErrorType || null, backoffSeconds:summary.openAIWebSearchBackoffSeconds || web.backoffSeconds || null, openAIWebSearchCacheHit:(web.cacheHits || 0)>0, openAIWebSearchCallsThisCycle:web.callsThisCycle || 0, finalProbabilitySource:source.finalProbabilitySource || source.probabilitySource || null, finalDecisionSource:source.finalDecisionSource || ((source.decisionSource === 'FEATHERLESS_AI' || (source.decisionSource === 'CACHE' && String(source.dataSource || source.probabilitySource).includes('FEATHERLESS'))) && ['error','timeout'].includes(summary.openAIWebSearchStatus || web.latestSearchStatus) ? 'FEATHERLESS_AI_WITHOUT_WEB_ENRICHMENT' : source.decisionSource || null), traces:summary.aiObservability || [] }; }
function buildSettlementFrequency(runs) { const hourAgo=Date.now()-3600000; const recent=runs.filter(run=>new Date(run.startedAt || run.created_date || 0).getTime()>=hourAgo); return {runsLastHour:recent.length,overlappingRuns:recent.filter((run,index)=>recent.some((other,otherIndex)=>otherIndex!==index&&new Date(other.startedAt).getTime()<new Date(run.completedAt || Date.now()).getTime()&&new Date(other.completedAt || Date.now()).getTime()>new Date(run.startedAt).getTime())).length,triggerCounts:recent.reduce((out,run)=>({...out,[run.triggerMode || 'unknown']:(out[run.triggerMode || 'unknown']||0)+1}),{})}; }
function buildRaceIdentityConsistency(markets,opportunities,orders,report) { const selected=report.selectedRaceKey; const rows=[...markets,...opportunities,...orders].map(item=>({type:item.opportunityId?'opportunity':item.customerRef||item.status?'order':'market',id:item.opportunityId||item.id||idOf(item),storedRaceKey:item.canonicalRaceKey||item.raceKey||null,resolvedRaceKey:canonicalRaceIdentity(item).canonicalRaceKey})); return {selectedRaceKey:selected,consistent:rows.every(row=>!row.storedRaceKey||row.storedRaceKey===row.resolvedRaceKey)&&opportunities.every(item=>!selected||!item.raceKey||item.raceKey===selected),mismatches:rows.filter(row=>row.storedRaceKey&&row.storedRaceKey!==row.resolvedRaceKey),opportunityRaceKeyMismatches:opportunities.filter(item=>selected&&item.raceKey&&item.raceKey!==selected).map(item=>item.opportunityId)}; }
function buildSchemaCheck(state, cycles, opportunities, raceMonitoring, riskExposure) { const duplicateRunKeys=cycles.filter(row=>row.cycleRunKey).filter((row,index,all)=>all.findIndex(other=>other.cycleRunKey===row.cycleRunKey)!==index).map(row=>row.cycleRunKey); const schedulers=[...new Set((state.botCycles || []).map(cycle=>cycle.schedulerInstanceId).filter(Boolean))]; const inconsistentOrders=(state.paperOrders || []).filter(order=>['won','lost','void'].includes(order.result)&&!['settled','voided'].includes(order.settlementStatus)); const awaitingMissingLock=(state.paperOrders || []).filter(order=>order.status==='awaiting_result'||order.settlementStatus==='awaiting_result').filter(order=>order.canonicalRaceKey===raceMonitoring.selectedRaceKey&&!raceMonitoring.raceLocked); const betGate=cycles.filter(row=>row.decision==='BET'&&Number(row.orderCreated)>0&&row.failedGate); const checks={marketsArray:Array.isArray(state.markets),runnersArray:Array.isArray(state.runners),paperOrdersArray:Array.isArray(state.paperOrders),botCyclesArray:Array.isArray(state.botCycles),decisionRows:cycles.length,opportunityRows:opportunities.length,duplicateConcurrentCycleRunKeys:duplicateRunKeys,multipleSchedulerInstances:schedulers.length>1?schedulers:[],awaitingResultMissingFromRaceLock:awaitingMissingLock.map(order=>order.id),resultWithUnsettledStatus:inconsistentOrders.map(order=>order.id),unresolvedOrdersMissingFromRiskExposure:riskExposure.activeOrderCount<(state.paperOrders || []).filter(order=>['matched','awaiting_result','result_unknown'].includes(order.status)).length,betCycleWithFailedGate:betGate.map(row=>row.cycleId)}; return {checkedAt:new Date().toISOString(),valid:Object.values(checks).every(value=>Array.isArray(value)?value.length===0:value!==false),checks}; }
function buildReadme(s) { return `BETFAIR EDGE LAB DEBUG PACKAGE\n\nApp name: ${s.appName}\nExport timestamp: ${s.exportTimestamp}\nCurrent page: ${s.currentPage}\nCurrent mode: ${s.mode}\nPaper mode: ${s.paperMode}\nProof mode: ${s.proofMode}\nBot status: ${s.botStatus}\nBetfair API connected: ${s.apiConnected}\nStream connected: ${s.streamConnected}\nPrice feed status: ${s.priceFeedStatus}\nWindow mode: ${s.windowMode}\nTime window start seconds: ${s.timeWindowStartSeconds}\nTime window end seconds: ${s.timeWindowEndSeconds}\n${s.windowWarning ? `Warning: ${s.windowWarning}\n` : ''}Selected race: ${s.selectedRace?.name || 'None'}\nMarkets: ${s.markets}\nRunners: ${s.runners}\nOpportunities: ${s.opportunities}\nPaper orders: ${s.paperOrders}\nUnresolved settlements: ${s.unresolvedSettlements}\nLatest cycle decision: ${s.latestCycleDecision || 'None'}\nLatest failed gate: ${s.latestFailedGate || 'None'}\nLatest no-bet reason: ${s.latestNoBetReason || 'None'}\n\nThis package contains no Betfair password, OpenAI key, Featherless key, Base44 secret, session token or private credential.\n`; }