import { describe, expect, it } from 'vitest';
import JSZip from 'jszip';
import { buildDebugPackage } from './debugPackageBuilder';
import { createDebugPackageFiles, FULL_DEBUG_PATHS, MINIMAL_DEBUG_PATHS } from './debugPackageFiles';
import { deepRedact } from './debugRedaction';

const opportunity = index => ({ cycleId:'c1',cycleNumber:1,rank:index,opportunityId:`o${index}`,raceKey:'r1',marketId:'1.1',marketName:'Win',marketType:'WIN',runnerName:'Runner',runnerNameHydrated:true,runnerNameHydrationSource:'catalogue',selectionId:String(index),side:'BACK',odds:2,availableSize:20,modelProbability:.55,finalProbabilityUsedInEV:.55,probabilitySource:'FEATHERLESS_AI',impliedProbability:.5,fairOdds:1.82,edge:.05,ev:1,roi:.1,confidence:70,dataQuality:80,decision:'NO_BET',gatesPassed:false,failedGate:'EDGE_BELOW_THRESHOLD',blocker:'EDGE_BELOW_THRESHOLD',blockers:['EDGE_BELOW_THRESHOLD'],decisionSource:'FEATHERLESS_AI',externalSearchStatus:'error',aiStatus:'Used',normalizedCommissionRate:.06,stake:10,liability:10,maxProfit:10,maxLoss:10,breakevenProbability:.5,mathematicalInvariantsPassed:true});
const opportunities=Array.from({length:19},(_,index)=>opportunity(index+1));
const cycle={cycleId:'c1',cycleNumber:1,finishedAt:'2026-07-11T22:30:00Z',ordersCreated:0,scanSummary:{selectedRaceKey:'r1',selectedRaceName:'Race 1',selectedRaceMarketDetails:[{marketId:'1.1',accepted:true}],opportunityLog:opportunities,totalOpportunities:19,bestRejectedCandidate:opportunities[0],bestRejectedCandidateId:'o1'}};
const state={settings:{defaultCommissionRate:.05,useMarketBaseRate:true},botSettings:{},featherlessSettings:{},botState:{running:false},apiConnected:true,betfairConnection:{streamConnectionStatus:'connected'},markets:[{betfairMarketId:'1.1',marketTypeCode:'WIN',marketBaseRate:6}],runners:[{marketId:'1.1',selectionId:'1',runnerName:'Runner',status:'ACTIVE',bestBackPrice:2,bestBackSize:20,bestLayPrice:2.02,bestLaySize:20},{marketId:'1.1',selectionId:'2',runnerName:'Runner 2',status:'ACTIVE',bestBackPrice:3,bestBackSize:20,bestLayPrice:3.05,bestLaySize:20}],paperOrders:[{id:'p1',status:'matched'}],botCycles:[cycle],auditLogs:[],aiDecisions:[],exchangeOpportunities:opportunities,lastExchangeDiagnostics:cycle.scanSummary,localStorageSnapshot:{sessionToken:'secret-session'},currentPage:'/debug'};

it('contains every required full file',async()=>{const result=await buildDebugPackage(state,{outputType:'uint8array'});const zip=await JSZip.loadAsync(result.blob);expect(FULL_DEBUG_PATHS.every(path=>zip.file(path))).toBe(true);});
it('minimal package contains only minimal files',()=>{const result=createDebugPackageFiles(state,{minimal:true});expect(Object.keys(result.files).sort()).toEqual([...MINIMAL_DEBUG_PATHS].sort());});
it('redacts secrets recursively',()=>{expect(deepRedact({nested:{password:'pw',apiKey:'key',items:[{accessToken:'token'}]}})).toEqual({nested:{password:'[REDACTED]',apiKey:'[REDACTED]',items:[{accessToken:'[REDACTED]'}]}});});
it('exports one decision row and nineteen opportunity rows',()=>{const result=createDebugPackageFiles(state);expect(result.files['cycles/decision-log.csv'].trim().split('\n')).toHaveLength(2);expect(result.files['opportunities/opportunity-log.csv'].trim().split('\n')).toHaveLength(20);});
it('includes canonical calculations and commission normalization',()=>{const result=createDebugPackageFiles(state);const calculations=JSON.parse(result.files['calculations/calculation-snapshots.json']);const commissions=JSON.parse(result.files['calculations/commission-snapshots.json']);expect(calculations[0]).toMatchObject({ev:1,roi:.1,normalizedCommissionRate:.06});expect(commissions.markets[0]).toMatchObject({rawMarketBaseRate:6,normalizedCommissionRate:.06,normalizationApplied:true});});
it('includes selected race market details',()=>{const result=createDebugPackageFiles(state);expect(JSON.parse(result.files['race-day/selected-race-market-details.json'])).toEqual([{marketId:'1.1',accepted:true}]);});
it('still builds when an optional section failed',async()=>{const result=await buildDebugPackage(state,{outputType:'uint8array',exportErrors:[{section:'AuditLog',error:'offline'}]});const zip=await JSZip.loadAsync(result.blob);expect(zip.file('errors/export-errors.json')).toBeTruthy();});
it('contains no credential values',async()=>{const result=await buildDebugPackage({...state,betfairConnection:{appKey:'secret-app'},localStorageSnapshot:{accessToken:'secret-token'}},{outputType:'uint8array'});const zip=await JSZip.loadAsync(result.blob);const texts=await Promise.all(Object.values(zip.files).filter(file=>!file.dir).map(file=>file.async('string')));expect(texts.join('\n')).not.toMatch(/secret-app|secret-token|secret-session/);});