import { describe, expect, it } from 'vitest';
import { buildDecisionLogging } from './decisionLogging';
import { cycleToRow, opportunitiesToRows } from './decisionLogExport';

const opportunity = (index, patch={}) => ({ opportunityId:`opp-${index}`, raceKey:'race-1', marketId:'1.1', marketName:'Win', marketType:'WIN', runnerName:`Runner ${index}`, selectionId:String(index), side:index%2?'BACK':'LAY', odds:2+index/10, availableSize:20, modelProbability:.4, finalProbabilityUsedInEV:.4, impliedProbability:.35, fairOdds:2.5, edge:.05, ev:.1, roi:.05, confidence:60, dataQuality:70, decision:'NO_BET', failedGate:'EDGE_BELOW_MINIMUM', blocker:'EDGE_BELOW_MINIMUM', blockers:['EDGE_BELOW_MINIMUM'], ...patch });
const build = (opportunities, patch={}) => buildDecisionLogging({opportunities,runners:patch.runners || [],cycleId:patch.cycleId || 'c1',cycleNumber:patch.cycleNumber || 1,raceKey:'race-1',finalSelectedOpportunity:patch.finalSelectedOpportunity || null,previousCycle:patch.previousCycle || null,aiStatus:'Used'});

it('exports one row for every generated opportunity', () => { const log=build(Array.from({length:19},(_,i)=>opportunity(i+1))); const rows=opportunitiesToRows([{cycleId:'c1',cycleNumber:1,scanSummary:log}]); expect(rows).toHaveLength(19); expect(new Set(rows.map(row=>row.opportunityId)).size).toBe(19); });
it('cycle summary does not use one unlabelled runner for the whole scan', () => { const log=build([opportunity(1),opportunity(2)]); const row=cycleToRow({cycleId:'c1',cycleNumber:1,ordersCreated:0,scanSummary:{...log,totalOpportunities:2}}); expect(row.runnerName).toBeUndefined(); expect(row.finalSelectedOpportunityId).toBe(''); expect(row.bestRejectedCandidateId).toBe('opp-1'); });
it('blocker and runner come from the same best rejected object', () => { const log=build([opportunity(1,{runnerName:'Tango Tango',blocker:'EDGE_BELOW_MINIMUM'}),opportunity(2)]); const row=cycleToRow({cycleId:'c1',cycleNumber:1,ordersCreated:0,scanSummary:log}); expect(row.bestRejectedRunnerName).toBe(log.bestRejectedCandidate.runnerName); expect(row.bestRejectedBlocker).toBe(log.bestRejectedCandidate.blocker); });
it('selected opportunity id matches the final selected object', () => { const selected=opportunity(2,{decision:'BET',gatesPassed:true}); const log=build([selected,opportunity(1)],{finalSelectedOpportunity:selected}); expect(log.finalSelectedOpportunityId).toBe(log.finalSelectedOpportunity.opportunityId); });
it('no-bet cycles populate best rejected candidate id', () => { expect(build([opportunity(1)]).bestRejectedCandidateId).toBe('opp-1'); });
it('same race keeps the same candidate only when inputs are unchanged', () => { const first=build([opportunity(1)]); const previousCycle={scanSummary:{...first,selectedRaceKey:'race-1'}}; const unchanged=build([opportunity(1)],{cycleId:'c2',cycleNumber:2,previousCycle}); const changed=build([opportunity(1,{odds:3})],{cycleId:'c3',cycleNumber:3,previousCycle}); expect(unchanged.bestRejectedChangedSincePreviousCycle).toBe(false); expect(unchanged.priceChangedSincePreviousCycle).toBe(false); expect(changed.priceChangedSincePreviousCycle).toBe(true); });
it('hydrates runner names from catalogue', () => { const log=build([opportunity(1,{runnerName:'Selection 1'})],{runners:[{marketId:'1.1',selectionId:'1',runnerName:'Tango Tango'}]}); expect(log.bestRejectedCandidate).toMatchObject({runnerName:'Tango Tango',runnerNameHydrated:true,runnerNameHydrationSource:'betfair_catalogue'}); });
it('clearly labels selection-only fallback as unhydrated', () => { const log=build([opportunity(97210897,{runnerName:'Selection 97210897'})]); expect(log.bestRejectedCandidate).toMatchObject({runnerName:'Selection 97210897',runnerNameHydrated:false,runnerNameHydrationSource:'missing_catalogue_name'}); });