// Mock data for the Featherless AI demo run.
// Represents a realistic Australian horse race at Flemington.

export const MOCK_RACE_PACK = {
  raceId: "1.209302145",
  eventId: "1.209302145",
  eventName: "Flemington R4",
  venue: "Flemington",
  countryCode: "AU",
  raceNumber: 4,
  startTime: "2026-07-10T03:35:00.000Z",
  secondsToJump: 287,
  trackCondition: "Good 4",
  distance: 1400,
  raceClass: "BM78",
  numberOfRunners: 8,
  numberOfActiveRunners: 8,

  marketSummary: {
    winMarket: { marketId: "1.209302145", totalMatched: 84250 },
    placeMarket: { marketId: "1.209302146", totalMatched: 18200 },
    h2hMarkets: [
      { marketId: "1.209302150", marketName: "I'm Thunderstruck v Magical Charm" },
      { marketId: "1.209302151", marketName: "I'm Thunderstruck v Argyle Pink" },
    ],
    totalMatched: 102450,
    marketBaseRate: 0.05,
    inPlay: false,
    status: "OPEN",
  },

  markets: [
    {
      marketId: "1.209302145",
      marketName: "Flemington R4 (BM78) WIN",
      marketType: "WIN",
      marketTypeCode: "WIN",
      status: "OPEN",
      inPlay: false,
      totalMatched: 84250,
      numberOfWinners: 1,
      marketBaseRate: 0.05,
      runners: [
        { selectionId: "41072231", runnerName: "I'm Thunderstruck", status: "ACTIVE", sortPriority: 1, bestBackPrice: 3.25, bestBackSize: 510, bestLayPrice: 3.30, bestLaySize: 340, lastPriceTraded: 3.25, tradedVolume: 28400, spreadTicks: 1, impliedBackProbability: 0.3077, impliedLayProbability: 0.3030, liquidityScore: 1.0 },
        { selectionId: "41072232", runnerName: "Magical Charm", status: "ACTIVE", sortPriority: 2, bestBackPrice: 4.60, bestBackSize: 280, bestLayPrice: 4.80, bestLaySize: 190, lastPriceTraded: 4.70, tradedVolume: 15200, spreadTicks: 3, impliedBackProbability: 0.2174, impliedLayProbability: 0.2083, liquidityScore: 0.56 },
        { selectionId: "41072233", runnerName: "Argyle Pink", status: "ACTIVE", sortPriority: 3, bestBackPrice: 6.00, bestBackSize: 165, bestLayPrice: 6.20, bestLaySize: 120, lastPriceTraded: 6.00, tradedVolume: 9800, spreadTicks: 2, impliedBackProbability: 0.1667, impliedLayProbability: 0.1613, liquidityScore: 0.33 },
        { selectionId: "41072234", runnerName: "Coastal Blaze", status: "ACTIVE", sortPriority: 4, bestBackPrice: 8.00, bestBackSize: 95, bestLayPrice: 8.50, bestLaySize: 80, lastPriceTraded: 8.20, tradedVolume: 6400, spreadTicks: 3, impliedBackProbability: 0.1250, impliedLayProbability: 0.1176, liquidityScore: 0.19 },
        { selectionId: "41072235", runnerName: "Night Raid", status: "ACTIVE", sortPriority: 5, bestBackPrice: 11.00, bestBackSize: 70, bestLayPrice: 12.00, bestLaySize: 55, lastPriceTraded: 11.50, tradedVolume: 4200, spreadTicks: 3, impliedBackProbability: 0.0909, impliedLayProbability: 0.0833, liquidityScore: 0.14 },
        { selectionId: "41072236", runnerName: "Stellar Moment", status: "ACTIVE", sortPriority: 6, bestBackPrice: 17.00, bestBackSize: 45, bestLayPrice: 19.00, bestLaySize: 30, lastPriceTraded: 18.00, tradedVolume: 2100, spreadTicks: 4, impliedBackProbability: 0.0588, impliedLayProbability: 0.0526, liquidityScore: 0.09 },
        { selectionId: "41072237", runnerName: "Dashing Valor", status: "ACTIVE", sortPriority: 7, bestBackPrice: 26.00, bestBackSize: 25, bestLayPrice: 29.00, bestLaySize: 20, lastPriceTraded: 27.00, tradedVolume: 850, spreadTicks: 4, impliedBackProbability: 0.0385, impliedLayProbability: 0.0345, liquidityScore: 0.05 },
        { selectionId: "41072238", runnerName: "Frozen Crown", status: "ACTIVE", sortPriority: 8, bestBackPrice: 41.00, bestBackSize: 15, bestLayPrice: 51.00, bestLaySize: 10, lastPriceTraded: 46.00, tradedVolume: 300, spreadTicks: 3, impliedBackProbability: 0.0244, impliedLayProbability: 0.0196, liquidityScore: 0.03 },
      ],
    },
    {
      marketId: "1.209302146",
      marketName: "Flemington R4 (BM78) PLACE",
      marketType: "PLACE",
      marketTypeCode: "PLACE",
      status: "OPEN",
      inPlay: false,
      totalMatched: 18200,
      numberOfWinners: 3,
      marketBaseRate: 0.05,
      runners: [
        { selectionId: "41072231", runnerName: "I'm Thunderstruck", status: "ACTIVE", sortPriority: 1, bestBackPrice: 1.50, bestBackSize: 820, bestLayPrice: 1.55, bestLaySize: 600, lastPriceTraded: 1.52, tradedVolume: 5600, spreadTicks: 2, impliedBackProbability: 0.6667, impliedLayProbability: 0.6452, liquidityScore: 1.0 },
        { selectionId: "41072232", runnerName: "Magical Charm", status: "ACTIVE", sortPriority: 2, bestBackPrice: 1.90, bestBackSize: 450, bestLayPrice: 2.02, bestLaySize: 320, lastPriceTraded: 1.95, tradedVolume: 3400, spreadTicks: 4, impliedBackProbability: 0.5263, impliedLayProbability: 0.4950, liquidityScore: 0.77 },
        { selectionId: "41072233", runnerName: "Argyle Pink", status: "ACTIVE", sortPriority: 3, bestBackPrice: 2.40, bestBackSize: 280, bestLayPrice: 2.60, bestLaySize: 200, lastPriceTraded: 2.50, tradedVolume: 2400, spreadTicks: 3, impliedBackProbability: 0.4167, impliedLayProbability: 0.3846, liquidityScore: 0.48 },
        { selectionId: "41072234", runnerName: "Coastal Blaze", status: "ACTIVE", sortPriority: 4, bestBackPrice: 3.00, bestBackSize: 180, bestLayPrice: 3.25, bestLaySize: 140, lastPriceTraded: 3.10, tradedVolume: 1600, spreadTicks: 3, impliedBackProbability: 0.3333, impliedLayProbability: 0.3077, liquidityScore: 0.32 },
        { selectionId: "41072235", runnerName: "Night Raid", status: "ACTIVE", sortPriority: 5, bestBackPrice: 4.00, bestBackSize: 120, bestLayPrice: 4.50, bestLaySize: 80, lastPriceTraded: 4.20, tradedVolume: 900, spreadTicks: 3, impliedBackProbability: 0.2500, impliedLayProbability: 0.2222, liquidityScore: 0.20 },
        { selectionId: "41072236", runnerName: "Stellar Moment", status: "ACTIVE", sortPriority: 6, bestBackPrice: 5.50, bestBackSize: 60, bestLayPrice: 6.50, bestLaySize: 40, lastPriceTraded: 6.00, tradedVolume: 400, spreadTicks: 4, impliedBackProbability: 0.1818, impliedLayProbability: 0.1538, liquidityScore: 0.10 },
        { selectionId: "41072237", runnerName: "Dashing Valor", status: "ACTIVE", sortPriority: 7, bestBackPrice: 8.00, bestBackSize: 30, bestLayPrice: 10.00, bestLaySize: 20, lastPriceTraded: 9.00, tradedVolume: 150, spreadTicks: 4, impliedBackProbability: 0.1250, impliedLayProbability: 0.1000, liquidityScore: 0.05 },
        { selectionId: "41072238", runnerName: "Frozen Crown", status: "ACTIVE", sortPriority: 8, bestBackPrice: 12.00, bestBackSize: 15, bestLayPrice: 17.00, bestLaySize: 10, lastPriceTraded: 14.00, tradedVolume: 50, spreadTicks: 5, impliedBackProbability: 0.0833, impliedLayProbability: 0.0588, liquidityScore: 0.03 },
      ],
    },
  ],

  runners: [
    { selectionId: "41072231", runnerName: "I'm Thunderstruck", status: "ACTIVE", barrier: 3, jockey: "James McDonald", trainer: "Ciaron Maher", weight: 58.5, age: 4, sex: "Gelding", form: "1-2-1-3-1", winMarketPrice: 3.25, placeMarketPrice: 1.50, h2hPrices: [{ marketId: "1.209302150", bestBackPrice: 1.85, bestLayPrice: 2.05 }, { marketId: "1.209302151", bestBackPrice: 1.65, bestLayPrice: 1.80 }], totalMatched: 28400, bestBackPrice: 3.25, bestLayPrice: 3.30, spreadTicks: 1, liquidity: 1.0, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
    { selectionId: "41072232", runnerName: "Magical Charm", status: "ACTIVE", barrier: 5, jockey: "Damian Lane", trainer: "Anthony Freedman", weight: 57.0, age: 5, sex: "Mare", form: "3-1-2-4-2", winMarketPrice: 4.60, placeMarketPrice: 1.90, h2hPrices: [{ marketId: "1.209302150", bestBackPrice: 2.10, bestLayPrice: 2.30 }], totalMatched: 15200, bestBackPrice: 4.60, bestLayPrice: 4.80, spreadTicks: 3, liquidity: 0.56, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
    { selectionId: "41072233", runnerName: "Argyle Pink", status: "ACTIVE", barrier: 1, jockey: "Jye McNeil", trainer: "Mick Price", weight: 56.5, age: 4, sex: "Mare", form: "2-3-1-1-4", winMarketPrice: 6.00, placeMarketPrice: 2.40, h2hPrices: [{ marketId: "1.209302151", bestBackPrice: 2.30, bestLayPrice: 2.60 }], totalMatched: 9800, bestBackPrice: 6.00, bestLayPrice: 6.20, spreadTicks: 2, liquidity: 0.33, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
    { selectionId: "41072234", runnerName: "Coastal Blaze", status: "ACTIVE", barrier: 7, jockey: "Craig Williams", trainer: "Matt Laurie", weight: 58.0, age: 6, sex: "Gelding", form: "4-4-3-2-3", winMarketPrice: 8.00, placeMarketPrice: 3.00, h2hPrices: [], totalMatched: 6400, bestBackPrice: 8.00, bestLayPrice: 8.50, spreadTicks: 3, liquidity: 0.19, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
    { selectionId: "41072235", runnerName: "Night Raid", status: "ACTIVE", barrier: 2, jockey: "Michael Dee", trainer: "Danny O'Brien", weight: 55.5, age: 3, sex: "Filly", form: "5-1-5-2-5", winMarketPrice: 11.00, placeMarketPrice: 4.00, h2hPrices: [], totalMatched: 4200, bestBackPrice: 11.00, bestLayPrice: 12.00, spreadTicks: 3, liquidity: 0.14, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
    { selectionId: "41072236", runnerName: "Stellar Moment", status: "ACTIVE", barrier: 8, jockey: "Ben Melham", trainer: "Gai Waterhouse", weight: 55.0, age: 4, sex: "Mare", form: "6-5-6-3-6", winMarketPrice: 17.00, placeMarketPrice: 5.50, h2hPrices: [], totalMatched: 2100, bestBackPrice: 17.00, bestLayPrice: 19.00, spreadTicks: 4, liquidity: 0.09, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
    { selectionId: "41072237", runnerName: "Dashing Valor", status: "ACTIVE", barrier: 6, jockey: "Jamie Kah", trainer: "Tony McEvoy", weight: 54.5, age: 5, sex: "Gelding", form: "7-6-8-5-7", winMarketPrice: 26.00, placeMarketPrice: 8.00, h2hPrices: [], totalMatched: 850, bestBackPrice: 26.00, bestLayPrice: 29.00, spreadTicks: 4, liquidity: 0.05, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
    { selectionId: "41072238", runnerName: "Frozen Crown", status: "ACTIVE", barrier: 4, jockey: "Luke Nolen", trainer: "Peter Moody", weight: 54.0, age: 3, sex: "Colt", form: "8-8-7-6-8", winMarketPrice: 41.00, placeMarketPrice: 12.00, h2hPrices: [], totalMatched: 300, bestBackPrice: 41.00, bestLayPrice: 51.00, spreadTicks: 3, liquidity: 0.03, publicResearch: null, positiveSignals: [], negativeSignals: [], notes: "" },
  ],

  externalResearch: {
    openAiSearchUsed: false,
    searchStatus: "disabled",
    sourceCount: 0,
    sources: [],
    raceSummary: "",
    runnerResearch: [],
  },

  settingsUsed: {
    enabledMarketTypes: ["WIN", "PLACE", "H2H"],
    minOdds: 1.5,
    maxOdds: 50,
    minLiquidity: 20,
    maxSpreadTicks: 7,
    minEdge: 3,
    minROI: 1,
    minConfidence: 50,
    maxStake: 500,
    maxLayLiability: 1500,
    timeWindow: { startSeconds: 500, endSeconds: 30 },
  },

  botContext: {
    paperMode: true,
    paperProofMode: false,
    bankroll: 10000,
    currentExposure: 0,
    dailyPnL: 0,
    weeklyPnL: 0,
    openOrdersInRace: 0,
    previousBetsOnRace: 0,
    commissionRate: 0.05,
    delayedApiMode: true,
    dataFreshness: "live",
    riskLimits: {
      dailyLossLimit: 500,
      weeklyLossLimit: 2500,
      maxMarketExposure: 1000,
      maxOpenOrders: 10,
      maxLayLiability: 1500,
    },
  },
};

export const MOCK_FEATHERLESS_RESPONSE = {
  decisionSource: "FEATHERLESS_RACE_ASSESSMENT",
  raceId: "1.209302145",
  eventId: "1.209302145",
  eventName: "Flemington R4",
  dataQuality: 68,
  confidence: 62,
  raceSummary: "BM78 over 1400m at Flemington. I'm Thunderstruck is the class runner with Jye McDonald aboard, strong form line. Market is liquid and well-formed. Magical Charm is the main danger with good place consistency.",
  marketRead: "WIN market overround 1.7% — efficient. Total matched $84K indicates strong each-way interest. I'm Thunderstruck's price has firmed from 3.50 to 3.25 in the last 10 minutes, suggesting informed money.",
  keyRisks: [
    "No external form data — probabilities based on market + Betfair metadata only",
    "Wide spread on outsiders (4+ ticks) reduces confidence in longshot pricing",
    "Barrier draw impact unverified without form data",
  ],
  runnerProbabilities: [
    {
      selectionId: "41072231",
      runnerName: "I'm Thunderstruck",
      pWin: 0.32,
      pPlace: 0.68,
      confidence: 72,
      fairWinOdds: 3.13,
      fairPlaceOdds: 1.47,
      positiveSignals: ["Jockey James McDonald — leading metropolitan rider", "Consistent form: 1-2-1-3-1", "Price firming from 3.50 → 3.25 (informed money)", "Ciaron Maher stable in form"],
      negativeSignals: ["Carries 58.5kg — top weight", "Barrier 3 — may get trapped on the rails"],
      reasoning: "Class runner of the field with superior form and elite jockey. Market agrees with assessment. Slightly over-bet as favourite but justified given form profile.",
      dataQuality: 75,
    },
    {
      selectionId: "41072232",
      runnerName: "Magical Charm",
      pWin: 0.22,
      pPlace: 0.55,
      confidence: 60,
      fairWinOdds: 4.55,
      fairPlaceOdds: 1.82,
      positiveSignals: ["Damian Lane — strong big-race jockey", "Anthony Freedman stable", "Good place consistency: 3-1-2-4-2"],
      negativeSignals: ["Wide barrier 5", "Mare against geldings at weight concession"],
      reasoning: "Main danger to the favourite. Place market suggests over 50% place chance which aligns with form. Win price looks about right.",
      dataQuality: 65,
    },
    {
      selectionId: "41072233",
      runnerName: "Argyle Pink",
      pWin: 0.17,
      pPlace: 0.45,
      confidence: 55,
      fairWinOdds: 5.88,
      fairPlaceOdds: 2.22,
      positiveSignals: ["Inside barrier 1 — advantage at Flemington", "Jye McNeil — tactically astute", "Improving form: 2-3-1-1-4"],
      negativeSignals: ["Mick Price stable quiet lately"],
      reasoning: "Inside draw and improving form make her a genuine each-way chance. Fair odds 5.88 vs market 6.00 — minimal value but place appeal is strong.",
      dataQuality: 60,
    },
    {
      selectionId: "41072234",
      runnerName: "Coastal Blaze",
      pWin: 0.12,
      pPlace: 0.35,
      confidence: 45,
      fairWinOdds: 8.33,
      fairPlaceOdds: 2.86,
      positiveSignals: ["Craig Williams — proven at this level"],
      negativeSignals: ["6YO — may be past peak", "Form tapering: 4-4-3-2-3", "Barrier 7 — wide trip likely"],
      reasoning: "Honest runner but form is plateauing. Market price of 8.00 looks fair — no edge either way.",
      dataQuality: 50,
    },
    {
      selectionId: "41072235",
      runnerName: "Night Raid",
      pWin: 0.08,
      pPlace: 0.25,
      confidence: 40,
      fairWinOdds: 12.50,
      fairPlaceOdds: 4.00,
      positiveSignals: ["3YO filly with upside", "Danny O'Brien stable"],
      negativeSignals: ["Inconsistent: 5-1-5-2-5", "Stepping up in class"],
      reasoning: "Inconsistent filly with ability but hasn't strung two together. Fair odds 12.50 vs market 11.00 — market has her slightly over-priced based on upside.",
      dataQuality: 45,
    },
    {
      selectionId: "41072236",
      runnerName: "Stellar Moment",
      pWin: 0.05,
      pPlace: 0.15,
      confidence: 35,
      fairWinOdds: 20.00,
      fairPlaceOdds: 6.67,
      positiveSignals: ["Gai Waterhouse — always tries"],
      negativeSignals: ["Poor form: 6-5-6-3-6", "Barrier 8 — worst draw", "Wide spread on this runner"],
      reasoning: "Out of form and wide barrier. Market price of 17.00 is shorter than my fair of 20.00 — no value.",
      dataQuality: 40,
    },
    {
      selectionId: "41072237",
      runnerName: "Dashing Valor",
      pWin: 0.03,
      pPlace: 0.10,
      confidence: 30,
      fairWinOdds: 33.33,
      fairPlaceOdds: 10.00,
      positiveSignals: ["Jamie Kah — can get more out of them"],
      negativeSignals: ["Form poor: 7-6-8-5-7", "Low liquidity — only $850 matched"],
      reasoning: "Outside chance at best. Fair odds 33.33 vs market 26.00 — market is too short. Potential LAY candidate but liquidity too thin.",
      dataQuality: 35,
    },
    {
      selectionId: "41072238",
      runnerName: "Frozen Crown",
      pWin: 0.01,
      pPlace: 0.04,
      confidence: 25,
      fairWinOdds: 100.00,
      fairPlaceOdds: 25.00,
      positiveSignals: [],
      negativeSignals: ["Worst form in the field: 8-8-7-6-8", "3YO colt stepping up significantly", "Almost no liquidity — $300 matched"],
      reasoning: "Roughie with no form to recommend. Market price of 41.00 is well short of fair 100.00. Clear LAY candidate but liquidity makes it untradeable.",
      dataQuality: 30,
    },
  ],
  h2hProbabilities: [
    {
      marketId: "1.209302150",
      selectionId: "41072231",
      runnerName: "I'm Thunderstruck",
      opponentSelectionId: "41072232",
      opponentName: "Magical Charm",
      pBeatsOpponent: 0.59,
      fairOdds: 1.69,
      confidence: 65,
      reasoning: "Superior form, better jockey, and market support favour the favourite in this matchup.",
    },
    {
      marketId: "1.209302151",
      selectionId: "41072231",
      runnerName: "I'm Thunderstruck",
      opponentSelectionId: "41072233",
      opponentName: "Argyle Pink",
      pBeatsOpponent: 0.65,
      fairOdds: 1.54,
      confidence: 68,
      reasoning: "Class advantage is clear here. I'm Thunderstruck should beat Argyle Pink more often than not.",
    },
  ],
  recommendedOpportunities: [
    {
      marketId: "1.209302145",
      marketType: "WIN",
      selectionId: "41072231",
      runnerName: "I'm Thunderstruck",
      side: "BACK",
      modelProbability: 0.32,
      fairOdds: 3.13,
      betfairOdds: 3.25,
      estimatedEdge: 3.8,
      estimatedROI: 4.0,
      confidence: 72,
      reasoning: "Fair odds 3.13 vs available 3.25. Positive edge with high confidence and good liquidity.",
      risks: ["Top weight 58.5kg", "No external form data"],
    },
    {
      marketId: "1.209302146",
      marketType: "PLACE",
      selectionId: "41072233",
      runnerName: "Argyle Pink",
      side: "BACK",
      modelProbability: 0.45,
      fairOdds: 2.22,
      betfairOdds: 2.40,
      estimatedEdge: 7.5,
      estimatedROI: 8.0,
      confidence: 55,
      reasoning: "Fair place odds 2.22 vs available 2.40. Inside barrier and improving form give strong place chance.",
      risks: ["Only 55% confidence", "Place market spread is 3 ticks"],
    },
    {
      marketId: "1.209302145",
      marketType: "WIN",
      selectionId: "41072237",
      runnerName: "Dashing Valor",
      side: "LAY",
      modelProbability: 0.03,
      fairOdds: 33.33,
      betfairOdds: 26.00,
      estimatedEdge: 22.0,
      estimatedROI: 27.0,
      confidence: 30,
      reasoning: "Fair odds 33.33 vs lay price 26.00. Market is too short. LAY value but liquidity is thin.",
      risks: ["Very low liquidity ($850 matched)", "Low confidence — only 30", "Wide spread 4 ticks"],
    },
  ],
  noBetReasons: [
    { reason: "No external form data available — confidence capped at 65 for market-only mode", severity: "warning", affectedMarketId: null, affectedSelectionId: null },
    { reason: "Wide spreads on runners 6-8 reduce pricing confidence on outsiders", severity: "info", affectedMarketId: "1.209302145", affectedSelectionId: null },
  ],
  finalRaceView: {
    bestRunner: "I'm Thunderstruck",
    mostOverpricedRunner: "Argyle Pink",
    mostUnderpricedRunner: "Dashing Valor",
    bestBackCandidate: "I'm Thunderstruck",
    bestLayCandidate: "Dashing Valor",
    shouldBetThisRace: true,
    summaryReason: "BACK I'm Thunderstruck at 3.25 — fair 3.13, 3.8% edge, 72% confidence, strong liquidity.",
  },
};