// ============================================================================
// Strategy Library — Betfair Exchange racing trading strategies
// These are the app's strategy catalog definitions (entry rules, exit rules,
// risk profiles, time windows, Betfair-specific parameters). All performance
// metrics are derived at runtime from live paper order data.
// ============================================================================

export const STRATEGY_LIBRARY = [
  {
    id: 'sl1',
    name: 'Value Bet',
    category: 'Value Betting',
    status: 'active',
    description: 'Identifies runners where the model probability exceeds the implied market probability, creating positive expected value opportunities. Uses historical form data, track conditions, barrier draw, weight allocation, and runner form to generate a fair odds estimate. When the Betfair back price exceeds the fair odds by at least the edge threshold, a BACK signal is generated.',
    entryRules: 'Model probability > implied probability by at least 2%. Minimum edge threshold of 5%. Odds between 1.50 and 20.00. Minimum liquidity $5,000 on the exchange. Runner must have at least 3 career starts for form analysis.',
    exitRules: 'Settle at race completion. No early exit — this is a straight win/place bet. Paper order auto-created when risk checks pass. Commission (5%) deducted from winning bets only.',
    riskProfile: 'Medium',
    marketTypes: ['WIN', 'PLACE'],
    timeWindow: 'Pre-race (10min – 30sec before start)',
    minEdge: 5.0,
    minLiquidity: 5000,
    createdAt: '2026-01-15T00:00:00+10:00',
    lastRun: null,
  },
  {
    id: 'sl2',
    name: 'Pre-Off Scalping',
    category: 'Scalping',
    status: 'active',
    description: 'Exploits tightening spreads in the final minutes before race start. Enters a BACK bet when the back/lay spread narrows to 1-2 ticks, then immediately places a LAY bet one tick lower to lock in a small guaranteed profit. High frequency, low risk per trade. Works best on highly liquid markets where the spread is tight and both sides have sufficient size.',
    entryRules: 'Back/lay spread ≤ 3 ticks. Market within time window (300s – 30s before start). Minimum liquidity $5,000. Traded volume > $10,000. Both back and lay sides must have at least $200 available at the target price.',
    exitRules: 'Exit on opposite side for 1-3 tick profit. Stop loss at 5 ticks from entry. Auto-cancel if spread widens beyond 5 ticks or if liquidity drops below $200 on either side.',
    riskProfile: 'Low',
    marketTypes: ['WIN', 'PLACE'],
    timeWindow: 'Pre-race (5min – 30sec before start)',
    minEdge: 1.5,
    minLiquidity: 5000,
    createdAt: '2026-01-20T00:00:00+10:00',
    lastRun: null,
  },
  {
    id: 'sl3',
    name: 'Fav/Outsider',
    category: 'Directional',
    status: 'active',
    description: 'Bets on favourites or outsiders based on market inefficiencies in small-field (2-3 runner) markets. Backs undervalued favourites where the market has over-reacted to a recent poor run, or lays overbacked outsiders where the implied probability is too high. Uses closing line value (CLV) analysis to detect mispricing. Currently underperforming — under review for possible retirement.',
    entryRules: 'Market has 2-3 runners. Favourite odds < 3.0 or outsider odds > 5.0. CLV analysis suggests mispricing of at least 2%. Minimum liquidity $3,000.',
    exitRules: 'Settle at race completion. No early exit.',
    riskProfile: 'Medium-High',
    marketTypes: ['WIN'],
    timeWindow: 'Pre-race (5min – 30sec before start)',
    minEdge: 2.0,
    minLiquidity: 3000,
    createdAt: '2026-02-10T00:00:00+10:00',
    lastRun: null,
  },
  {
    id: 'sl4',
    name: 'Steam/Drift',
    category: 'Momentum',
    status: 'active',
    description: 'Detects significant odds movements on the Betfair exchange — "steaming" (odds shortening) indicates money coming for a runner, while "drifting" (odds lengthening) indicates money against. Enters in the direction of momentum. Confirms signals by comparing Betfair odds with external bookmaker odds to detect divergence. Uses a 60-second rolling window for movement detection.',
    entryRules: 'Odds moved > 10% in 60 seconds on Betfair. External bookmaker odds diverge from Betfair by > 5%. Volume increasing (traded volume in last 5 min > 20% of total). Minimum liquidity $8,000.',
    exitRules: 'Exit when momentum reverses (odds move > 5% in opposite direction) or at race start. Stop loss at 8 ticks from entry.',
    riskProfile: 'High',
    marketTypes: ['WIN', 'PLACE'],
    timeWindow: 'Pre-race (10min – 30sec before start)',
    minEdge: 3.0,
    minLiquidity: 8000,
    createdAt: '2026-03-05T00:00:00+10:00',
    lastRun: null,
  },
  {
    id: 'sl7',
    name: 'Featherless AI Value Decision Engine',
    category: 'AI Value Betting',
    status: 'active',
    description: 'Uses Betfair historical data, form data and live Betfair market data to estimate true runner probabilities, detect value against the exchange price, and paper trade or optionally send validated bets to the Bot Control Centre. Powered by Featherless AI (OpenAI-compatible API). Every decision is validated by the app safety gate before any paper trade is created.',
    entryRules: 'AI confidence >= 75%. Minimum edge 5%. Minimum expected ROI 3%. Odds 2.00-12.00. Time window 30-300 seconds before jump. Max 1 bet per race. Max stake 1% bankroll. Confidence-weighted 25% Kelly staking. Paper trade only by default.',
    exitRules: 'Settle at race completion. Compare paper trade against BSP/closing price for CLV analysis.',
    riskProfile: 'Medium',
    marketTypes: ['WIN', 'PLACE'],
    timeWindow: 'Pre-race (5min – 30sec before start)',
    minEdge: 5.0,
    minLiquidity: 5000,
    createdAt: '2026-07-07T00:00:00+10:00',
    lastRun: null,
  },
  {
    id: 'sl5',
    name: 'In-Play Front Runner',
    category: 'In-Play',
    status: 'archived',
    description: 'Backed front-running horses in-play when they led by > 2 lengths, aiming to lay off at shorter odds as the horse maintained its lead. Archived due to high volatility and unreliable data feeds during in-play periods — Betfair in-play latency was too high to execute reliably.',
    entryRules: 'Horse leading by > 2 lengths (via live stream confirmation). In-play market active. Odds < 3.0. Stream confirmed live with < 2s latency.',
    exitRules: 'Exit when lead drops below 1 length or at race finish. Lay at 1-2 ticks shorter than entry.',
    riskProfile: 'High',
    marketTypes: ['WIN'],
    timeWindow: 'In-play only',
    minEdge: 4.0,
    minLiquidity: 10000,
    createdAt: '2026-01-05T00:00:00+10:00',
    lastRun: null,
  },
  {
    id: 'sl6',
    name: 'Cross-Market Arbitrage',
    category: 'Arbitrage',
    status: 'archived',
    description: 'Exploited pricing discrepancies between Betfair WIN/PLACE markets and external bookmakers. Archived due to diminishing opportunities (bookmakers now use Betfair as their reference price) and account restrictions from bookmakers.',
    entryRules: 'Arbitrage margin > 2% after 5% Betfair commission. Both sides available with sufficient liquidity. Bookmaker bet placed simultaneously.',
    exitRules: 'Exit immediately when margin closes. Both sides must be matched simultaneously.',
    riskProfile: 'Low',
    marketTypes: ['WIN', 'PLACE'],
    timeWindow: 'Pre-race (any time)',
    minEdge: 2.0,
    minLiquidity: 5000,
    createdAt: '2026-01-10T00:00:00+10:00',
    lastRun: null,
  },
];

// Betfair-specific enrichment fields per strategy
const STRATEGY_BETFAIR_FIELDS = {
  'Value Bet': {
    allowInPlay: false,
    timeWindowStart: 600,
    timeWindowEnd: 30,
    persistenceType: 'LAPSE',
    sideRestriction: 'BACK',
    requiresCommission: true,
    requiresCLV: true,
    paperOnly: true,
    validationStatus: 'promising',
    statusLabel: 'Promising — Paper Testing',
  },
  'Pre-Off Scalping': {
    allowInPlay: false,
    timeWindowStart: 300,
    timeWindowEnd: 30,
    persistenceType: 'LAPSE',
    sideRestriction: 'BOTH',
    requiresCommission: true,
    requiresCLV: false,
    requiresSlippage: true,
    requiresTightSpread: true,
    paperOnly: true,
    validationStatus: 'promising',
    statusLabel: 'Promising — Paper Testing',
  },
  'Fav/Outsider': {
    allowInPlay: false,
    timeWindowStart: 300,
    timeWindowEnd: 30,
    persistenceType: 'LAPSE',
    sideRestriction: 'BOTH',
    requiresCommission: true,
    requiresCLV: true,
    paperOnly: true,
    validationStatus: 'needs_more_data',
    statusLabel: 'Paper Testing',
    status: 'active',
  },
  'Steam/Drift': {
    allowInPlay: false,
    timeWindowStart: 600,
    timeWindowEnd: 30,
    persistenceType: 'LAPSE',
    sideRestriction: 'BOTH',
    requiresCommission: true,
    requiresCLV: false,
    requiresPriceMovement: true,
    paperOnly: true,
    validationStatus: 'needs_more_data',
    statusLabel: 'Needs More Data — Paper Only',
  },
  'Featherless AI Value Decision Engine': {
    allowInPlay: false,
    timeWindowStart: 300,
    timeWindowEnd: 30,
    persistenceType: 'LAPSE',
    sideRestriction: 'BACK',
    requiresCommission: true,
    requiresCLV: true,
    paperOnly: true,
    validationStatus: 'needs_more_data',
    statusLabel: 'AI Strategy — Paper Testing',
  },
  'In-Play Front Runner': {
    allowInPlay: true,
    timeWindowStart: 0,
    timeWindowEnd: 0,
    persistenceType: 'PERSIST',
    sideRestriction: 'BOTH',
    requiresCommission: true,
    requiresCLV: false,
    paperOnly: true,
    validationStatus: 'archived',
    statusLabel: 'Archived — Disabled',
    status: 'archived',
  },
  'Cross-Market Arbitrage': {
    allowInPlay: false,
    timeWindowStart: 600,
    timeWindowEnd: 0,
    persistenceType: 'LAPSE',
    sideRestriction: 'BOTH',
    requiresCommission: true,
    requiresCLV: false,
    paperOnly: true,
    validationStatus: 'archived',
    statusLabel: 'Archived — Disabled',
    status: 'archived',
  },
};

export const ENRICHED_STRATEGY_LIBRARY = STRATEGY_LIBRARY.map(s => ({
  ...s,
  ...STRATEGY_BETFAIR_FIELDS[s.name],
}));