import { createClientFromRequest } from 'npm:@base44/sdk@0.8.37';

const ACTIVE_ORDER_STATES=new Set(['matched','partially_matched','awaiting_result','result_unknown']);
const ACTIVE_SETTLEMENT_STATES=new Set(['pending','awaiting_result','result_unknown']);
const OPEN_MARKETS=new Set(['OPEN','SUSPENDED']);
const GRACE_SECONDS=90;
const LOCK_TTL_MS=4*60*1000;
const clean=value=>String(value ?? '').trim();
const normalize=value=>clean(value).toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const errorResponse=(code,message,status,extra={})=>Response.json({error:code,errorCode:code,errorMessage:message,...extra},{status});
const credentials=()=>({credentialSource:'backend_environment',appKeyConfigured:!!Deno.env.get('BETFAIR_APP_KEY'),usernameConfigured:!!Deno.env.get('BETFAIR_USERNAME'),passwordConfigured:!!Deno.env.get('BETFAIR_PASSWORD')});
const dueAt=(order,graceSeconds)=>new Date(order.raceStartTime || order.marketStartTime || 0).getTime()+graceSeconds*1000;
const retryAt=(attempts,now)=>new Date(now.getTime()+Math.min(1800,60*(2**Math.max(0,attempts)))*1000).toISOString();

async function proxyPost(url,headers,payload){const proxy=Deno.env.get('BETFAIR_PROXY_URL');if(!proxy)throw new Error('BETFAIR_PROXY_URL_NOT_SET');const response=await fetch(`${proxy}?url=${encodeURIComponent(url)}`,{method:'POST',headers,body:payload});const text=await response.text();if(!response.ok||text.trimStart().startsWith('<!DOCTYPE')||text.includes('<html'))throw new Error(`BETFAIR_HTTP_${response.status}`);const parsed=JSON.parse(text);if(parsed?.faultcode||parsed?.error)throw new Error(`BETFAIR_ERROR:${JSON.stringify(parsed).slice(0,200)}`);return parsed;}
async function login(){const appKey=Deno.env.get('BETFAIR_APP_KEY'),username=Deno.env.get('BETFAIR_USERNAME'),password=Deno.env.get('BETFAIR_PASSWORD');if(!appKey||!username||!password)throw new Error('BETFAIR_CREDENTIALS_NOT_SET');const headers={'X-Application':appKey,'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'};const body=`username=${encodeURIComponent(username)}&password=${encodeURIComponent(password)}`;let result=await proxyPost('https://identitysso-cert.betfair.com/api/certlogin',headers,body);let token=result.token||result.sessionToken;if((!token||result.status!=='SUCCESS')&&result.loginStatus==='CERT_AUTH_REQUIRED'){result=await proxyPost('https://identitysso.betfair.com/api/login',headers,body);token=result.token||result.sessionToken;}if(!token)throw new Error(`BETFAIR_LOGIN_FAILED:${result.loginStatus||result.error||'NO_TOKEN'}`);const createdAt=new Date();return{appKey,token,createdAt:createdAt.toISOString(),expiresAt:new Date(createdAt.getTime()+12*3600000).toISOString()};}
async function fetchBooks(ids,session){if(!ids.length)return[];const jurisdiction=Deno.env.get('BETFAIR_JURISDICTION')||'AU';const base=jurisdiction==='AU'?'https://api.betfair.com.au':'https://api.betfair.com';const headers={'X-Application':session.appKey,'X-Authentication':session.token,'Content-Type':'application/json',Accept:'application/json'};const books=[];for(let i=0;i<ids.length;i+=10){const batch=await proxyPost(`${base}/exchange/betting/rest/v1.0/listMarketBook/`,headers,JSON.stringify({marketIds:ids.slice(i,i+10),priceProjection:{priceData:['EX_TRADED']}}));if(Array.isArray(batch))books.push(...batch);}return books;}
function commissionRate(order){const raw=Number(order.normalizedCommissionRate ?? order.commissionRateUsed ?? .05);const rate=raw>1?raw/100:raw;if(!Number.isFinite(rate)||rate<0||rate>.2)throw new Error('INVALID_COMMISSION');return rate;}
function calculation(order,winners){const selectedWon=winners.includes(clean(order.normalizedSelectionId||order.selectionId));const stake=Number(order.matchedStake??order.matched_size)||0;const odds=Number(order.matchedOdds??order.matched_price)||0;const liability=Number(order.liability)||stake*Math.max(0,odds-1);const betWon=order.side==='LAY'?!selectedWon:selectedWon;const grossProfit=order.side==='LAY'?(selectedWon?-liability:stake):(selectedWon?stake*(odds-1):-stake);return{order,betWon,grossProfit};}

Deno.serve(async req=>{let base44=null,run=null;try{
  base44=createClientFromRequest(req);let body={};try{body=await req.json();}catch(_){ }
  const internal=['scheduled','workflow'].includes(body.trigger);let user=null;try{user=await base44.auth.me();}catch(_){ }
  if(!internal&&!user)return errorResponse('UNAUTHORIZED_MANUAL_REQUEST','Manual settlement requires an authenticated user',401);
  const now=new Date(),runId=crypto.randomUUID(),creds=credentials();
  const graceSeconds=Math.max(60,Math.min(120,Number(body.settlementGraceSeconds)||GRACE_SECONDS));
  if(body.action==='credential_status'){const latest=await base44.asServiceRole.entities.SettlementWorkerRun.list('-created_date',1);return Response.json({...creds,lastRun:latest?.[0]||null});}
  const recentRuns=await base44.asServiceRole.entities.SettlementWorkerRun.filter({status:'running'},'-startedAt',10);
  const activeRun=recentRuns.find(run=>now.getTime()-new Date(run.startedAt||0).getTime()<LOCK_TTL_MS);
  if(activeRun)return Response.json({workerStatus:'completed',settlementCheckStatus:'SKIPPED_OVERLAPPING_RUN',skipped:true,activeRunId:activeRun.runId,errorCode:null,checkedAt:now.toISOString()});
  const triggerMode=internal?'internal':'manual';
  run=await base44.asServiceRole.entities.SettlementWorkerRun.create({runId,lockKey:'paper-settlement-worker',triggerMode,requestingUserId:user?.id||null,startedAt:now.toISOString(),status:'running',...creds,ordersChecked:0,marketsChecked:0,ordersSettled:0,ordersVoided:0,ordersUnresolved:0});
  const finish=async details=>{const payload={runId,workerStatus:'completed',checkedAt:now.toISOString(),errorCode:null,...details};await base44.asServiceRole.entities.SettlementWorkerRun.update(run.id,{completedAt:new Date().toISOString(),status:'completed',errorCode:null,errorMessage:null,ordersChecked:payload.ordersChecked||0,marketsChecked:payload.marketsChecked||0,ordersSettled:payload.ordersSettled||0,ordersVoided:payload.ordersVoided||0,ordersUnresolved:payload.ordersUnresolved||0,lastLoginStatus:payload.currentSessionCreatedAt?'success':null,lastLoginError:null,currentSessionCreatedAt:payload.currentSessionCreatedAt||null,currentSessionExpiresAt:payload.currentSessionExpiresAt||null,details:payload});return Response.json(payload);};
  const all=await base44.asServiceRole.entities.PaperOrder.filter({},'-created_date',500);
  const repairs=all.filter(order=>['won','lost','void'].includes(order.result)&&!['settled','voided'].includes(order.settlementStatus)).map(order=>({id:order.id,status:order.result==='void'?'voided':'settled',settlementStatus:order.result==='void'?'voided':'settled',settledAt:order.settledAt||order.settled_date||now.toISOString(),settled_date:order.settled_date||order.settledAt||now.toISOString(),settlementError:null}));
  if(repairs.length)await base44.asServiceRole.entities.PaperOrder.bulkUpdate(repairs);
  const candidates=all.filter(order=>ACTIVE_ORDER_STATES.has(normalize(order.status))&&ACTIVE_SETTLEMENT_STATES.has(normalize(order.settlementStatus))&&!order.settledAt&&!['won','lost','void'].includes(order.result));
  const notDue=candidates.filter(order=>!Number.isFinite(dueAt(order,graceSeconds))||now.getTime()<dueAt(order,graceSeconds));
  const backoff=candidates.filter(order=>new Date(order.nextSettlementRetryAt||0).getTime()>now.getTime());
  const due=candidates.filter(order=>Number.isFinite(dueAt(order,graceSeconds))&&now.getTime()>=dueAt(order,graceSeconds)&&new Date(order.nextSettlementRetryAt||0).getTime()<=now.getTime());
  const statusUpdates=[...notDue.map(order=>({id:order.id,settlementCheckStatus:'NOT_DUE'})),...backoff.map(order=>({id:order.id,settlementCheckStatus:'RETRY_BACKOFF'}))];
  if(statusUpdates.length)await base44.asServiceRole.entities.PaperOrder.bulkUpdate(statusUpdates);
  if(!due.length)return finish({settlementCheckStatus:'NOT_DUE',settlementGraceSeconds:graceSeconds,ordersChecked:0,ordersNotDue:notDue.length,ordersInBackoff:backoff.length,marketsChecked:0,ordersSettled:0,ordersVoided:0,ordersUnresolved:0,repairsApplied:repairs.length});
  if(!creds.appKeyConfigured||!creds.usernameConfigured||!creds.passwordConfigured)throw new Error('BETFAIR_CREDENTIALS_NOT_SET');
  const session=await login();const groups=new Map();for(const order of due){const marketId=clean(order.normalizedMarketId||order.betfairMarketId||order.marketId);if(!marketId)continue;if(!groups.has(marketId))groups.set(marketId,[]);groups.get(marketId).push(order);}
  const books=await fetchBooks([...groups.keys()],session);const updates=[];let ordersSettled=0,ordersVoided=0,ordersUnresolved=0,marketsStillOpen=0,marketsClosed=0;
  for(const [marketId,orders] of groups){const book=books.find(item=>clean(item.marketId)===marketId);const status=String(book?.status||'UNAVAILABLE').toUpperCase();
    if(!book||OPEN_MARKETS.has(status)){if(book)marketsStillOpen++;for(const order of orders)updates.push({id:order.id,settlementCheckStatus:book?'NOT_DUE':'RESULT_DELAYED',settlementError:null,marketStatusAtLastCheck:status,settlementLastCheckedAt:now.toISOString(),settlementWorkerRunId:runId});continue;}
    marketsClosed++;const runners=Array.isArray(book.runners)?book.runners:[];const winners=runners.filter(item=>String(item.status||'').toUpperCase()==='WINNER').map(item=>clean(item.selectionId));const voided=book.voided===true||(runners.length>0&&runners.every(item=>['REMOVED','VOIDED'].includes(String(item.status||'').toUpperCase())));
    if(voided){for(const order of orders){ordersVoided++;updates.push({id:order.id,status:'voided',settlementStatus:'voided',result:'void',netPL:0,netProfit:0,grossProfit:0,commission:0,settledAt:now.toISOString(),settled_date:now.toISOString(),settlementError:null,resultSource:'BETFAIR_MARKET_BOOK',marketStatusAtSettlement:status,settlementCheckStatus:'SETTLED',voided:true});}continue;}
    if(!winners.length){for(const order of orders){const attempts=(order.settlementAttempts||0)+1;ordersUnresolved++;updates.push({id:order.id,status:'awaiting_result',settlementStatus:'result_unknown',settlementAttempts:attempts,settlementCheckStatus:'RESULT_DELAYED',settlementError:'MARKET_RESULT_NOT_AVAILABLE',nextSettlementRetryAt:retryAt(attempts,now),settlementLastCheckedAt:now.toISOString(),settlementWorkerRunId:runId,marketStatusAtLastCheck:status});}continue;}
    const rates=orders.map(commissionRate);if(rates.some(rate=>Math.abs(rate-rates[0])>1e-12))throw new Error('INCONSISTENT_MARKET_COMMISSION_RATES');
    const deadHeatDivisor=winners.length>Number(orders[0]?.numberOfWinners||1)?winners.length:1;const calculations=orders.map(order=>{const item=calculation(order,winners);if(deadHeatDivisor>1&&item.betWon&&order.side==='BACK'){const stake=Number(order.matchedStake??order.matched_size)||0,odds=Number(order.matchedOdds??order.matched_price)||0;item.grossProfit=stake*(odds/deadHeatDivisor-1);}return item;});const marketGross=calculations.reduce((sum,item)=>sum+item.grossProfit,0);const rate=rates[0];const marketCommission=marketGross>0?marketGross*rate:0;const positive=calculations.reduce((sum,item)=>sum+Math.max(0,item.grossProfit),0);
    for(const item of calculations){const commission=item.grossProfit>0&&positive>0?marketCommission*item.grossProfit/positive:0;const net=item.grossProfit-commission;ordersSettled++;updates.push({id:item.order.id,status:'settled',settlementStatus:'settled',result:item.betWon?'won':'lost',netPL:net,netProfit:net,grossProfit:item.grossProfit,commission,settledAt:now.toISOString(),settled_date:now.toISOString(),settlementError:null,resultSource:'BETFAIR_MARKET_BOOK',marketStatusAtSettlement:status,settlementCheckStatus:'SETTLED',winnerSelectionId:winners[0],winnerSelectionIds:winners,settlementLastCheckedAt:now.toISOString(),settlementWorkerRunId:runId,nextSettlementRetryAt:null});}
  }
  if(updates.length)await base44.asServiceRole.entities.PaperOrder.bulkUpdate(updates);
  return finish({settlementCheckStatus:'COMPLETED',settlementGraceSeconds:graceSeconds,ordersChecked:due.length,ordersNotDue:notDue.length,ordersInBackoff:backoff.length,marketsChecked:groups.size,marketsStillOpen,marketsClosed,ordersSettled,ordersVoided,ordersUnresolved,repairsApplied:repairs.length,currentSessionCreatedAt:session.createdAt,currentSessionExpiresAt:session.expiresAt});
}catch(error){if(base44&&run?.id){try{await base44.asServiceRole.entities.SettlementWorkerRun.update(run.id,{completedAt:new Date().toISOString(),status:'failed',errorCode:'SETTLEMENT_WORKER_FAILED',errorMessage:error.message,lastLoginStatus:'failed',lastLoginError:error.message});}catch(_){ }}return errorResponse('SETTLEMENT_WORKER_FAILED',error.message,500,{workerStatus:'failed',checkedAt:new Date().toISOString()});}});